apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: event-driven-sample
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: hsuliz/event-driven-sample/order-service
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: KAFKA_ORDER_TOPIC
              value: order-topic
            - name: KAFKA_ENGINE_TOPIC
              value: engine-topic
            - name: MONGODB_HOST
              value: mongodb:27017
            - name: MONGODB_DATABASE
              value: event-driven
            - name: MONGODB_USERNAME
              value: admin
            - name: MONGODB_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP