apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: event-driven-sample
build:
  artifacts:
    - image: hsuliz/event-driven-sample/engine-service
      docker:
        dockerfile: cmd/engine/Dockerfile
    - image: hsuliz/event-driven-sample/order-service
      docker:
        dockerfile: cmd/order/Dockerfile
deploy:
  helm:
    releases:
      - name: kafka
        remoteChart: bitnami/kafka
        version: 32.2.11
        valuesFiles:
          - infrastructure/values/kafka.yaml
      - name: mongodb
        remoteChart: bitnami/mongodb
        version: 16.5.20
        valuesFiles:
          - infrastructure/values/mongodb.yaml
manifests:
  rawYaml:
    - cmd/engine/k8s.yaml
    - cmd/order/k8s.yaml