listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
provisioning:
  enabled: true
  topics:
    - name: order-topic
      partitions: 1
      replicationFactor: 1
    - name: history-topic
      partitions: 1
      replicationFactor: 1