apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-service
  labels:
    app: event-driven-sample
spec:
  selector:
    matchLabels:
      app: engine-service
  template:
    metadata:
      labels:
        app: engine-service
    spec:
      containers:
        - name: engine-service
          image: hsuliz/event-driven-sample/engine-service
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: KAFKA_ENGINE_TOPIC
              value: engine-topic
            - name: KAFKA_ORDER_TOPIC
              value: order-topic
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  selector:
    app: engine-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP